/* Original music for this game. Generated by Web Audio; no external tracks or requests. */
const GAME_SCORES={
 explore:{name:'林間小步舞',bpm:112,root:60,scale:[0,2,4,5,7,9,11],chords:[0,3,4,0,5,3,4,0],lead:'triangle',energy:0,
 motifs:[[4,-1,6,-1,7,-1,9,7,6,-1,4,-1,2,-1,4,-1],[3,-1,5,-1,7,5,-1,3,2,-1,1,-1,0,-1,2,-1],[4,-1,6,7,-1,9,-1,7,6,4,-1,2,1,-1,2,-1],[2,-1,4,-1,6,-1,4,2,1,-1,0,-1,0,-1,-1,-1]]},
 battle:{name:'小徑交鋒',bpm:144,root:57,scale:[0,2,3,5,7,8,10],chords:[0,5,3,4,0,5,6,4],lead:'square',energy:1,
 motifs:[[0,0,4,-1,7,6,4,-1,3,4,6,-1,4,2,0,-1],[5,-1,7,5,4,-1,2,4,3,-1,4,3,2,1,0,-1],[0,2,4,7,-1,9,7,6,4,-1,6,7,6,4,2,-1],[3,4,6,-1,4,2,1,-1,0,2,4,2,0,-1,0,-1]]},
 lich:{name:'不死巫妖・永夜鐘聲',bpm:154,root:62,scale:[0,2,3,5,7,8,11],chords:[0,5,3,4,0,2,5,4],lead:'sine',energy:2,
 motifs:[[7,-1,6,7,9,-1,7,6,4,3,4,-1,6,4,3,1],[5,4,3,-1,2,3,5,-1,7,6,4,3,1,-1,0,-1],[0,4,7,6,7,9,10,-1,9,7,6,4,3,4,6,-1],[6,4,3,1,0,-1,6,-1,7,6,4,-1,1,0,-1,-1]]},
 dragon:{name:'火焰巨龍・熾翼追擊',bpm:168,root:50,scale:[0,2,3,5,7,8,10],chords:[0,0,5,6,3,5,4,4],lead:'sawtooth',energy:3,
 motifs:[[7,7,7,9,10,-1,9,7,6,7,9,10,11,-1,9,7],[5,5,7,9,10,9,7,-1,6,6,7,9,10,7,6,-1],[3,4,5,7,9,7,5,-1,4,5,6,7,10,9,7,-1],[6,7,9,10,9,7,6,4,7,6,4,-1,0,0,7,-1]]},
 ancient:{name:'遠古魔神・終焉脈動',bpm:180,root:47,scale:[0,1,3,5,7,8,10],chords:[0,1,0,5,3,1,6,0],lead:'square',energy:4,
 motifs:[[7,8,7,4,7,-1,6,4,3,4,6,7,8,-1,7,6],[8,7,4,3,1,0,1,-1,4,6,7,8,10,8,7,-1],[0,0,7,0,8,7,6,4,3,3,10,3,11,10,8,7],[6,7,8,10,11,10,8,7,6,4,3,1,0,-1,0,-1]]},
 victory:{name:'終於可以休假了',bpm:124,root:60,scale:[0,2,4,5,7,9,11],chords:[0,4,5,3,0,3,4,0],lead:'triangle',energy:0,
 motifs:[[0,-1,2,4,7,-1,7,-1,9,-1,7,-1,4,-1,-1,-1],[4,-1,6,-1,7,9,11,-1,9,-1,7,-1,6,-1,-1,-1],[5,-1,7,-1,9,7,5,-1,4,-1,2,-1,0,-1,2,-1],[4,6,7,-1,9,-1,7,-1,4,-1,2,-1,0,-1,-1,-1]]}
};
const MUSIC_PREF_KEY='jack-adventure.audio.v1';
function readMusicPrefs(){try{const p=JSON.parse(localStorage.getItem(MUSIC_PREF_KEY)||'{}');return {music:typeof p.music==='boolean'?p.music:true,sfx:typeof p.sfx==='boolean'?p.sfx:false,musicVolume:Number.isFinite(p.musicVolume)?Math.max(0,Math.min(1,p.musicVolume)):.32,sfxVolume:Number.isFinite(p.sfxVolume)?Math.max(0,Math.min(1,p.sfxVolume)):.45};}catch{return {music:true,sfx:false,musicVolume:.32,sfxVolume:.45};}}
function scorePitch(track,degree,octave=0){const scale=track.scale,n=scale.length;return track.root+scale[((degree%n)+n)%n]+12*Math.floor(degree/n)+12*octave;}
function frequency(midi){return 440*2**((midi-69)/12);}
function trackForScene(){if(['BATTLE','BATTLE_ACTION'].includes(gameState)&&currentEnemy){if(adventure.battle?.isBoss)return {'不死巫妖':'lich','火焰巨龍':'dragon','遠古魔神':'ancient'}[currentEnemy.name]||'battle';return 'battle';}return gameState==='CREDITS'?'victory':'explore';}
const Music={
 prefs:readMusicPrefs(),ctx:null,master:null,musicGain:null,sfxGain:null,noise:null,bus:null,timer:null,step:0,nextTime:0,track:null,unlocked:false,scheduled:0,switches:0,
 ensure(){
  if(this.ctx)return this.ctx;
  const Context=window.AudioContext||window.webkitAudioContext;if(!Context)throw new Error('此瀏覽器不支援音樂合成');
  const c=this.ctx=new Context(),compressor=c.createDynamicsCompressor();compressor.threshold.value=-18;compressor.knee.value=12;compressor.ratio.value=4;compressor.attack.value=.003;compressor.release.value=.18;
  this.master=c.createGain();this.master.gain.value=.26;this.master.connect(compressor);compressor.connect(c.destination);
  this.musicGain=c.createGain();this.musicGain.gain.value=this.prefs.musicVolume;this.musicGain.connect(this.master);
  this.sfxGain=c.createGain();this.sfxGain.gain.value=this.prefs.sfxVolume;this.sfxGain.connect(this.master);
  // Private deterministic noise does not consume gameplay Math.random().
  this.noise=c.createBuffer(1,Math.floor(c.sampleRate*.24),c.sampleRate);const a=this.noise.getChannelData(0);let seed=92117;for(let i=0;i<a.length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;a[i]=((seed/4294967296)*2-1)*(1-i/a.length);}
  return c;
 },
 unlock(){
  this.unlocked=true;
  try{if(!this.prefs.music&&!this.prefs.sfx){this.updateUI();return;}const c=this.ensure();Promise.resolve(c.resume()).then(()=>{if(!document.hidden)this.sync();}).catch(()=>this.updateUI());}catch{this.updateUI();}
 },
 savePrefs(){try{localStorage.setItem(MUSIC_PREF_KEY,JSON.stringify(this.prefs));}catch{}},
 setPreference(key,value){
  if(['music','sfx'].includes(key))this.prefs[key]=!!value;else if(['musicVolume','sfxVolume'].includes(key)&&Number.isFinite(value))this.prefs[key]=Math.max(0,Math.min(1,value));else return;
  this.savePrefs();if(this.ctx){this.musicGain.gain.setTargetAtTime(this.prefs.musicVolume,this.ctx.currentTime,.035);this.sfxGain.gain.setTargetAtTime(this.prefs.sfxVolume,this.ctx.currentTime,.035);}
  this.unlock();this.sync();this.updateUI();
 },
 sync(){
  const desired=trackForScene();
  if(!this.unlocked||!this.prefs.music||this.prefs.musicVolume===0||document.hidden||!this.ctx||this.ctx.state!=='running'){this.stop();this.updateUI();return;}
  if(this.track===desired&&this.timer!==null)return;
  this.stop();this.track=desired;this.step=0;this.nextTime=this.ctx.currentTime+.045;this.switches++;
  const gain=this.ctx.createGain();gain.gain.setValueAtTime(0,this.ctx.currentTime);gain.gain.linearRampToValueAtTime(1,this.ctx.currentTime+.18);gain.connect(this.musicGain);this.bus={gain,voices:new Set()};
  this.tick();this.timer=setInterval(()=>this.tick(),80);this.updateUI();
 },
 stop(){
  if(this.timer!==null){clearInterval(this.timer);this.timer=null;}
  if(this.bus&&this.ctx){const bus=this.bus,now=this.ctx.currentTime;bus.gain.gain.cancelScheduledValues(now);bus.gain.gain.setTargetAtTime(0,now,.035);for(const voice of bus.voices){try{voice.stop(now+.15);}catch{}}setTimeout(()=>bus.gain.disconnect(),200);}
  this.bus=null;this.track=null;
 },
 pause(){this.stop();if(this.ctx?.state==='running')this.ctx.suspend().catch(()=>{});this.updateUI();},
 tick(){
  if(!this.bus||!this.track||!this.ctx||this.ctx.state!=='running')return;
  const now=this.ctx.currentTime,track=GAME_SCORES[this.track],beat=60/track.bpm,stepDuration=beat/4;
  if(this.nextTime<now-.25)this.nextTime=now+.03;
  let count=0;while(this.nextTime<now+.18&&count++<12){this.scheduleStep(track,this.step,this.nextTime,stepDuration,this.bus);this.step=(this.step+1)%256;this.nextTime+=stepDuration;}
 },
 note(midi,time,duration,type,volume,bus,cutoff=2400){
  if(!this.ctx||bus.voices.size>80)return;const c=this.ctx,o=c.createOscillator(),gain=c.createGain(),filter=c.createBiquadFilter();o.type=type;o.frequency.value=frequency(midi);filter.type='lowpass';filter.frequency.value=cutoff;filter.Q.value=.5;
  gain.gain.setValueAtTime(0,time);gain.gain.linearRampToValueAtTime(volume,time+.012);gain.gain.setValueAtTime(volume*.7,time+Math.max(.018,duration*.45));gain.gain.exponentialRampToValueAtTime(.0001,time+duration+.08);
  o.connect(filter);filter.connect(gain);gain.connect(bus.gain);bus.voices.add(o);o.onended=()=>{bus.voices.delete(o);o.disconnect();filter.disconnect();gain.disconnect();};o.start(time);o.stop(time+duration+.1);this.scheduled++;
 },
 drum(kind,time,volume,bus){
  if(!this.ctx||bus.voices.size>80)return;const c=this.ctx,g=c.createGain();g.connect(bus.gain);let source,filter;
  if(kind==='kick'){source=c.createOscillator();source.type='sine';source.frequency.setValueAtTime(115,time);source.frequency.exponentialRampToValueAtTime(38,time+.12);source.connect(g);g.gain.setValueAtTime(volume,time);g.gain.exponentialRampToValueAtTime(.0001,time+.17);}
  else{source=c.createBufferSource();source.buffer=this.noise;filter=c.createBiquadFilter();filter.type='highpass';filter.frequency.value=kind==='hat'?6700:1200;source.connect(filter);filter.connect(g);g.gain.setValueAtTime(volume,time);g.gain.exponentialRampToValueAtTime(.0001,time+(kind==='hat'?.035:.12));}
  bus.voices.add(source);source.onended=()=>{bus.voices.delete(source);source.disconnect();g.disconnect();if(filter)filter.disconnect();};source.start(time);source.stop(time+.2);this.scheduled++;
 },
 scheduleStep(t,index,time,d,bus){
  const step=index%16,bar=Math.floor(index/16),chord=t.chords[bar%t.chords.length],motif=t.motifs[bar%4],degree=motif[step],lift=bar>=8&&bar%4===2?7:0;
  if(degree>=0){this.note(scorePitch(t,degree+lift,1),time,d*(step===14?2.4:1.45),t.lead,t.energy>1?.12:.16,bus,t.energy>=3?1800:3400);if(t.energy===2)this.note(scorePitch(t,degree,0),time,d*1.8,'triangle',.07,bus);}
  if(step%(t.energy>=3?2:4)===0)this.note(scorePitch(t,chord+(step%8===4?4:0),-1),time,d*1.65,'triangle',.30,bus,650);
  if(step===0||step===8){for(const offset of [0,2,4])this.note(scorePitch(t,chord+offset),time,d*6,'triangle',.065,bus,1200);}
  if(step%2===1&&(t.energy>0||bar%2===1)){const degree=chord+[0,2,4,7][Math.floor(step/2)%4];this.note(scorePitch(t,degree,1),time,d*.65,'sine',t.energy>=2?.075:.07,bus);}
  if(t.energy===0){if(step===0||step===8)this.drum('kick',time,.10,bus);if(step===4||step===12)this.drum('hat',time,.05,bus);}
  else{if(step===0||step===8||(t.energy>=3&&[6,10].includes(step)))this.drum('kick',time,.38,bus);if(step===4||step===12||(bar%4===3&&step>=13&&t.energy>=2))this.drum('snare',time,.22,bus);if(step%(t.energy>=3?1:2)===0)this.drum('hat',time,.065,bus);}
  if(t.energy===4&&[3,7,11,15].includes(step))this.note(scorePitch(t,chord+7,1),time,d*.8,'sawtooth',.055,bus,1100);
 },
 sfx(kind){
  if(!this.unlocked||!this.prefs.sfx||this.prefs.sfxVolume===0||document.hidden)return;
  try{const c=this.ensure();if(c.state!=='running')return;const bus={gain:this.sfxGain,voices:new Set()};this.note(kind==='reward'?84:kind==='heal'?76:52,c.currentTime+.005,.11,'triangle',.20,bus);}catch{}
 },
 updateUI(){
  const active=this.track&&this.timer!==null,title=active?GAME_SCORES[this.track].name:(!this.prefs.music?'音樂已關閉':document.hidden?'背景分頁已暫停':this.unlocked?'等待播放':'開始／繼續冒險後播放');
  if($('music-now'))$('music-now').textContent=title;
  if($('music-status'))$('music-status').textContent=active?'♫ '+GAME_SCORES[this.track].name:'♫ '+title;
  for(const key of ['music','sfx']){const el=$(key+'-enabled');if(el)el.checked=this.prefs[key];const volume=$(key+'-volume');if(volume)volume.value=Math.round(this.prefs[key+'Volume']*100);const label=$(key+'-volume-value');if(label)label.textContent=`${Math.round(this.prefs[key+'Volume']*100)}%`;}
 }
};
function initMusic(){
 $('btn-sound').onclick=()=>{Music.unlock();Music.updateUI();$('audio-dialog').showModal();};
 for(const key of ['music','sfx']){
  $(key+'-enabled').onchange=e=>Music.setPreference(key,e.target.checked);
  $(key+'-volume').oninput=e=>Music.setPreference(key+'Volume',Number(e.target.value)/100);
 }
 for(const id of ['btn-new-game','btn-continue','btn-title-import','btn-title-slots']){
  const button=$(id),previous=button.onclick;
  button.onclick=function(e){Music.unlock();return previous?.call(this,e);};
 }
 document.addEventListener('visibilitychange',()=>{
  document.body.classList.toggle('page-hidden',document.hidden);
  if(document.hidden){Music.pause();saveAuto();}else if(Music.unlocked)Music.unlock();
 });
 window.addEventListener('pagehide',()=>{Music.pause();saveAuto();});
 Music.updateUI();
}
