/* Single-player NPC adventurers. No network players or external services. */
const NPC_ROSTER={
 moss:{name:'阿苔',title:'很會迷路的遊俠',look:'ranger',role:'斥候',nature:'嘴硬、喜歡當隊長',base:3,line:'我沒有迷路，是這條路還沒跟上我。'},
 lune:{name:'露娜',title:'欠睡眠的法師',look:'violet',role:'法師',nature:'毒舌但會照顧人',base:4,line:'我不是在打瞌睡，我在冥想你的智商。'},
 iron:{name:'鐵餅',title:'背鍋專用的盾衛',look:'jade',role:'守衛',nature:'老實、怕欠錢',base:4,line:'我扛得住傷害，扛不住房租。'},
 tink:{name:'小叮',title:'工具比朋友多的工匠',look:'smith',role:'工匠',nature:'熱心、工具不外借',base:3,line:'你的劍能修。你的操作我不保證。'},
 amber:{name:'阿栗',title:'不帶地圖的商旅',look:'merchant',role:'商人',nature:'精明、記得恩情',base:2,line:'朋友歸朋友，打折要看交情。'},
 snow:{name:'白梨',title:'堅稱自己是新手的劍士',look:'silver',role:'劍士',nature:'愛切磋、有輸有贏',base:5,line:'我才玩一下下。上一次是三百年前。'},
 snip:{name:'小剪',title:'手比嘴快的小偷',look:'shadow',role:'盜賊',nature:'膽小、跑得快',base:3,bad:true,line:'你的錢包剛才說想跟我回家。'},
 coin:{name:'金牙',title:'按人頭收費的路霸',look:'ruby',role:'路霸',nature:'貪財、欺軟怕硬',base:5,bad:true,line:'此路是我開，團體沒有優惠。'},
 brick:{name:'板磚',title:'不太懂搶劫的打手',look:'sentinel',role:'打手',nature:'力氣大、容易說服',base:4,bad:true,line:'老大說劫財。我以為他要借柴。'},
 ember:{name:'紅豆',title:'把補血當辣椒的牧師',look:'sun',role:'補給員',nature:'開朗、偶爾不靠譜',base:3,line:'喝下去會熱熱的，代表還活著！'}
};
for(const [id,n]of Object.entries(NPC_ROSTER))SCENE_PORTRAITS['npc_'+id]={...SCENE_PORTRAITS[n.look],id:'npc_'+id,name:n.name,kind:'person'};
const NPC_ENCOUNTERS={npc_party:{members:['moss','lune','iron'],place:'forest'},npc_rival:{members:['snow','tink'],place:'village'},npc_bandits:{members:['coin','brick','snip'],place:'road'},npc_pickpocket:{members:['snip','amber'],place:'market'},npc_ambush:{members:['amber','coin','brick'],place:'cave'},npc_tavern:{members:['moss','snow','ember'],place:'tavern'},npc_wounded:{members:['iron','lune'],place:'marsh'},npc_fake_guard:{members:['brick','coin'],place:'citadel'},npc_camp:{members:[],place:'village'}};
function ensureSocial(){const e=ensureExpedition();return e.social??={version:1,roster:{},active:[],event:null,campVisits:[],helper:null,helperBattles:0,lastHelpRound:0,lastHelpBattle:0,escapes:0,repute:0};}
function npcRecord(id){const s=ensureSocial();if(!s.roster[id]){const level=NPC_ROSTER[id].base+Math.max(0,bossLevel-1)*5;s.roster[id]={level,hp:25+level*7,maxHp:25+level*7,trust:0,meetings:0,wins:0,lastSeen:adventure.steps};}return s.roster[id];}
function npcMeet(id){const n=npcRecord(id);if(adventure.steps-n.lastSeen>=4){n.level=Math.min(40,n.level+1);n.maxHp=25+n.level*7;n.hp=Math.min(n.maxHp,n.hp+12);}n.meetings++;n.lastSeen=adventure.steps;}
function npcBond(ids,delta){for(const id of ids){const n=npcRecord(id);n.trust=Math.max(-5,Math.min(5,n.trust+delta));}}
function beginNpcEncounter(id){const s=ensureSocial(),spec=NPC_ENCOUNTERS[id];if(!spec){s.active=[];s.event=null;return;}s.event=id;if(id!=='npc_camp'){s.active=[...spec.members];if(id==='npc_party'&&runRandom()<.4)s.active=s.active.slice(0,2);}for(const n of s.active)npcMeet(n);ensureExpedition().place=id==='npc_camp'?settlementPlace():spec.place;}
function npcNames(){return ensureSocial().active.map(id=>NPC_ROSTER[id].name).join('、');}
function npcPanelMarkup(){const s=ensureSocial();if(!s.event||!s.active.length)return '';return `<div class="npc-profiles"><small>NPC 冒險者 · 單機模擬，不是真人連線</small>${s.active.map(id=>{const d=NPC_ROSTER[id],n=npcRecord(id);return `<section><strong>${d.name} <em>Lv.${n.level} · ${d.role}</em></strong><span>${d.title}</span><small>HP ${n.hp}/${n.maxHp} · ${d.nature} · 交情 ${n.trust>0?'+':''}${n.trust} · 相遇 ${n.meetings} 次</small><p>「${n.trust>=2?'是你啊，這次別再讓我一個人扛。':n.trust<=-2?'你上次的事，我還沒忘。':d.line}」</p></section>`;}).join('')}</div>`;}
function npcCheckChance(kind='escape',level=null){const n=level??Math.max(...ensureSocial().active.map(id=>npcRecord(id).level),hero.level);const base=kind==='talk'?36+hero.currentTieWinRate*.55+ensureSocial().repute*2:35+hero.currentDodge*.65;return Math.round(Math.max(15,Math.min(90,base+(hero.level-n)*3+(adventure.flags.fox&&kind==='escape'?5:0))));}
function npcEscapeHint(){return `逃離成功率 ${npcCheckChance('escape')}% · 依等級、閃避與狐狸；失敗遭突襲`;}
function npcTryEscape(ids=ensureSocial().active.filter(id=>NPC_ROSTER[id].bad)){const chance=npcCheckChance('escape');if(runRandom()*100<chance){ensureSocial().escapes++;resultEvent('你跑得很快，尊嚴勉強跟上','成功脫身，沒有戰利品，也沒有金幣損失。',88);}else{safeWound(.08);log(`🏃 逃離失敗（${chance}%）：擦傷 8% HP，對手追上來了。`);startNpcBattle(ids.length?ids:['snip']);}}
function npcNegotiate(ids=ensureSocial().active.filter(id=>NPC_ROSTER[id].bad)){const chance=npcCheckChance('talk');if(runRandom()*100<chance){npcBond(ids,1);ensureSocial().repute=Math.min(5,ensureSocial().repute+1);resultEvent('你說得太有道理，對方開始懷疑人生','交涉成功，沒有損失。他們打算先開會討論搶劫的必要性。',85);}else{log(`🗣 交涉失敗（${chance}%），對方決定用武器投票。`);startNpcBattle(ids.length?ids:['coin']);}}
function startNpcBattle(ids,duel=false,bounty=0){
 const s=ensureSocial();s.active=ids;s.event=duel?'npc_rival':'npc_bandits';for(const id of ids)npcRecord(id);const rank=Math.max(1,Math.min(38,hero.level+1)),count=ids.length;
 const hp=ids.reduce((sum,id)=>sum+npcRecord(id).hp,0),atk=Math.round(11+ids.reduce((sum,id)=>sum+npcRecord(id).level,0)/count*3.3+(count-1)*3),group=ids.map(id=>NPC_ROSTER[id].name).join('、');
 createBattle({name:duel?`${group}的切磋`:`${group}的盜賊隊`,hp,atk,def:Math.round(3+rank*.8),mDef:Math.round(2+rank*.65),dodge:ids.includes('snip')?22:10,exp:Math.floor(hero.expToNextLevel*(duel?.23:.38)),lootChance:duel?.65:1,bias:ids.includes('snip')?{'⚔️':.3,'🌠':.2,'🛡️':.5}:{'⚔️':.5,'🌠':.25,'🛡️':.25},npcIds:[...ids],npcBounty:Math.max(0,Math.min(50,bounty)),npcDuel:duel},false);
}
function recruitNpc(id){const s=ensureSocial();if(s.helper&&s.helperBattles>0){adventure.scoutTurns=Math.max(2,adventure.scoutTurns);resultEvent('隊伍不是無限大的，便當也不是','已有同行夥伴，這次交換情報：洞察至少 2 回合。',88);return;}s.helper=id;s.helperBattles=2;s.lastHelpRound=0;s.lastHelpBattle=0;npcBond([id],1);resultEvent(`${NPC_ROSTER[id].name}：這兩場我跟你走`,'接下來 2 場戰鬥，每第 4 回合追加你 ATK 的 15%＋其等級一半的傷害。之後重逢仍記得交情。',88);}
function npcSupport(){const s=ensureSocial(),b=adventure.battle;if(!s.helper||s.helperBattles<=0||!b||b.settled||gameState!=='BATTLE_ACTION'||b.round%4||hero.hp<=0||currentEnemy.hp<=0||(s.lastHelpRound===b.round&&s.lastHelpBattle===b.id))return 0;s.lastHelpRound=b.round;s.lastHelpBattle=b.id;const n=npcRecord(s.helper),dmg=Math.min(currentEnemy.hp,Math.max(2,Math.floor(hero.currentAttack*.15+n.level*.5)));currentEnemy.hp-=dmg;log(`🤝 ${NPC_ROSTER[s.helper].name} 支援 ${dmg} 傷害。`);return dmg;}
function npcBattleFinished(won){const s=ensureSocial();if(currentEnemy?.npcIds){for(const id of currentEnemy.npcIds){const n=npcRecord(id);if(won){n.hp=Math.max(1,Math.floor(n.maxHp*.25));npcBond([id],currentEnemy.npcDuel?1:-1);}else{n.wins++;n.hp=Math.max(1,Math.floor(n.maxHp*.7));}}if(won){const gold=8+Math.min(30,currentEnemy.npcIds.length*4+bossLevel*2)+(currentEnemy.npcBounty||0);adventure.gold+=gold;log(`🎒 NPC 戰利品：額外 ${gold} 金幣${currentEnemy.npcDuel?'，對手認輸並記住你':'，並可取得裝備'}。`);}}
 if(s.helper&&s.helperBattles>0){const n=npcRecord(s.helper);if(won)n.wins++;else n.hp=Math.max(1,Math.floor(n.hp*.7));s.helperBattles--;if(!s.helperBattles){log(`👋 ${NPC_ROSTER[s.helper].name} 先去補給，之後有緣再見。`);s.helper=null;}}
}
function battleEscapeChance(){return npcCheckChance('escape',currentEnemy?.npcIds?Math.max(...currentEnemy.npcIds.map(id=>npcRecord(id).level)):Math.max(1,hero.level+bossLevel-1));}
function tryBattleEscape(){const b=adventure.battle;if(!b||b.isBoss)return false;const chance=battleEscapeChance();if(runRandom()*100>=chance){log(`🏃 逃跑失敗（${chance}%）：放棄這回合攻擊，敵人追擊。`);return false;}b.settled=true;ensureSocial().escapes++;log(`🏃 逃跑成功（${chance}%），不發放經驗、金幣或戰利品。`);adventure.result={tag:'安全最重要',title:'打不過，至少還跑得動。',text:'你與同行夥伴成功撤離。這場沒有戰利品，下次準備好再來。',object:88};gameState='RESULT';renderResult();saveAuto();return true;}
function campResidents(){const ids=Object.keys(NPC_ROSTER).filter(id=>!NPC_ROSTER[id].bad),e=ensureExpedition(),start=(e.seed+e.chapter*3+e.depth)%ids.length;return [ids[start],ids[(start+2)%ids.length]];}
function meetCampNpc(id){if(gameState!=='MAP'||!campResidents().includes(id))return;const e=ensureExpedition(),s=ensureSocial(),key=`${e.chapter}:${e.depth}:${id}`;if(s.campVisits.includes(key)){toast(`${NPC_ROSTER[id].name}：剛不是聊過了嗎？先去冒險，回來再說。`);return;}s.campVisits.push(key);s.campVisits=s.campVisits.slice(-20);s.active=[id];enterEvent('npc_camp');revealCurrentContent();}
function renderNpcScene(mode){const layer=$('npc-scene-layer');if(!layer)return;const s=ensureSocial();const ids=gameState==='MAP'?campResidents():currentEnemy?.npcIds&&mode==='battle'?currentEnemy.npcIds:['EVENT','RESULT'].includes(gameState)&&s.event?s.active:[];layer.hidden=!ids.length;layer.replaceChildren();if(!ids.length)return;$('scene-object').hidden=true;$('scene-npc-name').hidden=true;if(mode==='battle')$('enemy-actor').hidden=true;
 for(const id of ids){const d=NPC_ROSTER[id],n=npcRecord(id),el=document.createElement(gameState==='MAP'?'button':'div');el.className='npc-scene-actor';el.dataset.npc=id;if(gameState==='MAP'){el.type='button';el.onclick=()=>meetCampNpc(id);el.title=`跟 ${d.name} 說話`;}const art=document.createElement('span');art.className='sprite';drawPortrait(art,'npc_'+id,56);const caption=document.createElement('small');caption.textContent=`${d.name} · Lv.${n.level}${gameState==='MAP'?' 💬':''}`;el.append(art,caption);layer.append(el);}
 if(currentEnemy?.npcIds&&mode==='battle')$('scene-caption').firstElementChild.textContent=`NPC ${ids.length} 人隊伍 · 血條是隊伍合計生命，可用逃跑撤離。`;else if(gameState==='MAP')$('scene-caption').firstElementChild.textContent='點人物可以聊聊；探索回來，村裡可能換了一批冒險者。';
}
function initNpcWorld(){const layer=document.createElement('div');layer.id='npc-scene-layer';layer.hidden=true;$('stage').append(layer);const flee=document.createElement('button');flee.id='tactic-flee';flee.textContent='逃跑';flee.title='普通敵人與盜賊可嘗試逃跑；失敗會被追擊。Boss 不可逃離。';flee.onclick=e=>{if(e.detail<=1)handleBattleAction('FLEE');};$('tactical-actions').append(flee);renderNpcScene(gameState==='BATTLE'?'battle':'map');}
