/* Encounter tuning uses synthetic equipment profiles; these are not human win-rate estimates. */
import {chromium} from 'playwright-core';import fs from 'node:fs';import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});
const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
try{
 await page.goto(process.env.GAME_URL||'http://127.0.0.1:8770/',{waitUntil:'networkidle'});
 const report=await page.evaluate(()=>{
  const results=[],examples=[],native=Math.random;const must=(ok,msg)=>{if(!ok)throw Error(msg);};
  const profile=(level=20,chapter=3)=>{confirmTitle();enterMap();bossLevel=chapter;hero.level=hero.highestLevel=level;hero.maxHp=hero.hp=20+(level-1)*4;hero.baseAttack=15+(level-1)*2;hero.baseDefense=10+(level-1)*2;hero.baseMagicAtk=20+(level-1)*4;hero.baseDodge=10;hero.baseTieWinRate=45;hero.equipment.WEAPON={type:'WEAPON',name:'參考長劍',power:50,rarity:'Rare',refine:0,refineSlots:0,affixes:[]};hero.equipment.SHIELD={type:'SHIELD',name:'參考盾',power:35,rarity:'Rare',refine:0,refineSlots:0,affixes:[]};updateStatus();Math.random=()=>.9;};
  const baseline=(i,zone=2)=>{const e=ENEMIES.SMALL[i],rank=Math.min(SCENES[zone].level+1,Math.max([1,7,12,19,26][zone],hero.level-1));return {...e,hp:Math.round(e.hp*(1+(rank-1)*.17)),atk:Math.round(9+(rank-1)*3.3),def:Math.round(e.def*(1+(rank-1)*.065)),mDef:Math.round(e.mDef*(1+(rank-1)*.065))};};
  const check=(name,fn)=>{profile();try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}};
  check('Profile evaluation neither mutates hero nor consumes gameplay RNG',()=>{const before=JSON.stringify(hero),rng=ensureExpedition().rng;let rolls=0;Math.random=()=>{rolls++;return .5;};for(let n=0;n<10;n++)encounterHeroProfile();must(before===JSON.stringify(hero)&&rolls===0&&ensureExpedition().rng===rng,'profile has side effects');});
  check('Opening chapter levels 1 through 7 retain their original ordinary enemy budgets',()=>{for(let level=1;level<=7;level++){hero.level=level;const e=baseline(0,0);must(JSON.stringify(scaleSmallEncounter(e,ENEMIES.SMALL[0],0))===JSON.stringify(e),'early fight changed');}});
  check('Mid-game normal enemies survive more than the previous tiny HP budget',()=>{const e=baseline(0),n=scaleSmallEncounter(e,ENEMIES.SMALL[0],2);must(n.hp>e.hp*1.5,'HP still trivial');must(n.atk>hero.currentDefense+hero.maxHp*.07,'hits still negligible');});
  check('Strong attack upgrades raise monster HP sublinearly and not its attack',()=>{const e=baseline(0),a=scaleSmallEncounter(e,ENEMIES.SMALL[0],2);hero.equipment.WEAPON.power+=140;updateStatus();const b=scaleSmallEncounter(e,ENEMIES.SMALL[0],2);must(b.hp>a.hp&&b.hp/a.hp<2,'offensive upgrade fully canceled');must(b.atk===a.atk,'attack reflected as enemy attack');});
  check('Magic equipment also contributes to encounter HP',()=>{const e=baseline(0),a=scaleSmallEncounter(e,ENEMIES.SMALL[0],2);hero.baseMagicAtk+=200;updateStatus();const b=scaleSmallEncounter(e,ENEMIES.SMALL[0],2);must(b.hp>a.hp,'magic build ignored');});
  check('Defense and maximum HP raise pressure without copying dodge or tie chances',()=>{const e=baseline(1),a=scaleSmallEncounter(e,ENEMIES.SMALL[1],2);hero.equipment.SHIELD.power+=80;hero.maxHp+=80;updateStatus();const b=scaleSmallEncounter(e,ENEMIES.SMALL[1],2);must(b.atk>a.atk,'survivability ignored');must(b.dodge===a.dodge&&JSON.stringify(b.bias)===JSON.stringify(a.bias),'copied player accuracy');});
  check('Current injury, temporary damage buff and armor-break do not reroll strength',()=>{const e=baseline(2),a=scaleSmallEncounter(e,ENEMIES.SMALL[2],2);hero.hp=1;hero.buffDamageUpTurns=4;hero.buffDamageUpRate=.5;hero.defDownTurns=3;hero.defDownRate=.3;updateStatus();const b=scaleSmallEncounter(e,ENEMIES.SMALL[2],2);must(JSON.stringify(a)===JSON.stringify(b),'temporary status changed scaling');});
  check('Active damage pets contribute partially; resting pets do not',()=>{const e=baseline(0),a=scaleSmallEncounter(e,ENEMIES.SMALL[0],2);adventure.pets={version:1,owned:['wolf','ember','griffin'],order:[],offer:null};const resting=scaleSmallEncounter(e,ENEMIES.SMALL[0],2);must(a.hp===resting.hp,'bench pets count');hero.equipment.RING={type:'RING',name:BEAST_RING.name,ability:BEAST_RING,tier:3,rarity:'Rare'};adventure.pets.order=['wolf','ember','griffin'];updateStatus();const b=scaleSmallEncounter(e,ENEMIES.SMALL[0],2);must(b.hp>a.hp&&b.hp<a.hp*1.6,'pet bonus fully canceled or ignored');});
  check('Rock, skeleton, wolf and bat keep different defenses and evasion',()=>{const a=ENEMIES.SMALL.map((e,i)=>scaleSmallEncounter(baseline(i),e,2));must(a[3].def>a[3].mDef&&a[2].mDef>a[2].def&&a[4].dodge>a[1].dodge,'archetypes homogenized');});
  check('Monsters freeze at encounter start and survive a real save round-trip',()=>{startSmallBattle(0);const old=JSON.stringify(currentEnemy);hero.baseAttack+=20;updateStatus();renderBattle();must(JSON.stringify(currentEnemy)===old,'rescaled in battle');applySave(parseSave(JSON.stringify(captureSave())));must(currentEnemy.adaptiveLevel===20,'snapshot marker lost');must(currentEnemy.hp===JSON.parse(old).hp&&currentEnemy.atk===JSON.parse(old).atk,'rescaled on load');});
  check('Existing unscaled fight loads with its original numbers',()=>{createBattle({...ENEMIES.SMALL[0],hp:77,atk:19});const d=captureSave();applySave(d);must(currentEnemy.hp===77&&currentEnemy.atk===19&&!currentEnemy.adaptiveLevel,'old encounter overwritten');});
  check('Bosses remain fixed regardless of hero equipment',()=>{const configs=JSON.stringify(ENEMIES.BOSS);for(let i=1;i<=5;i++){bossLevel=i;hero.baseAttack+=100;startBossBattle();must(currentEnemy.originalHp===ENEMIES.BOSS[i-1].hp&&currentEnemy.atk===ENEMIES.BOSS[i-1].atk&&!currentEnemy.adaptiveLevel,'boss scaled');}must(configs===JSON.stringify(ENEMIES.BOSS),'boss definitions mutated');});
  check('Elite encounters scale and still guarantee loot',()=>{startEliteBattle();must(currentEnemy.elite&&currentEnemy.adaptiveLevel===20&&currentEnemy.lootChance===1,'elite scaling missing');parseSave(JSON.stringify(captureSave()));});
  check('Malformed adaptive level is rejected without touching the ongoing battle',()=>{startSmallBattle(0);const d=captureSave(),before=JSON.stringify(captureSave().payload);d.payload.currentEnemy.adaptiveLevel=999;let fail=false;try{applySave(d);}catch{fail=true;}must(fail&&before===JSON.stringify(captureSave().payload),'bad metadata accepted');});
  for(const [level,chapter]of [[8,1],[12,2],[19,3],[26,4],[34,5]]){
   profile(level,chapter);const zone=chapter-1;
   for(let i=0;i<ENEMIES.SMALL.length;i++){const e=baseline(i,zone),n=scaleSmallEncounter(e,ENEMIES.SMALL[i],zone);examples.push({level,chapter,name:e.name,hero:{hp:hero.maxHp,atk:hero.currentAttack,def:hero.currentDefense,magic:getMagicAttackValue()},before:{hp:e.hp,atk:e.atk,def:e.def,mDef:e.mDef},after:{hp:n.hp,atk:n.atk,def:n.def,mDef:n.mDef},nominalHit:Math.max(1,n.atk-hero.currentDefense)});}
  }
  Math.random=native;return {results,examples};
 });
 fs.writeFileSync('encounter-balance-report.json',JSON.stringify({...report,errors},null,2));
 console.log(JSON.stringify({passed:report.results.filter(r=>r.pass).length,failed:report.results.filter(r=>!r.pass),examples:report.examples.filter(e=>e.name==='哥布林'),errors},null,2));
 assert.ok(report.results.every(r=>r.pass)&&errors.length===0);
}finally{await browser.close();}
