import {chromium} from 'playwright-core';import fs from 'node:fs';import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})}),page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
try{await page.goto(process.env.GAME_URL||'http://127.0.0.1:8770/',{waitUntil:'networkidle'});
const results=await page.evaluate(()=>{
 const results=[],oldRandom=Math.random,oldRunRandom=runRandom;
 const check=(name,fn)=>{confirmTitle();enterMap();try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}finally{Math.random=oldRandom;runRandom=oldRunRandom;}};
 const assert=(v,why)=>{if(!v)throw Error(why);};const saved=()=>parseSave(JSON.stringify(captureSave()));
 check('Village has two named clickable NPCs, not a static ranger',()=>{assert(document.querySelectorAll('#npc-scene-layer button').length===2,'missing residents');const id=campResidents()[0];meetCampNpc(id);assert(gameState==='EVENT'&&adventure.eventId==='npc_camp','not interactive');assert(npcPanelMarkup().includes('單機模擬'),'NPC label absent');});
 check('Camp dialogue cannot be farmed without exploring',()=>{const id=campResidents()[0];meetCampNpc(id);chooseEvent(0);enterMap();const n=npcRecord(id).meetings;meetCampNpc(id);assert(gameState==='MAP'&&npcRecord(id).meetings===n,'same camp encounter repeat');});
 check('NPC bond and identity survive saves',()=>{enterEvent('npc_party');npcBond(['moss'],2);const n=JSON.stringify(npcRecord('moss')),ids=JSON.stringify(ensureSocial().active);applySave(saved());assert(JSON.stringify(npcRecord('moss'))===n&&JSON.stringify(ensureSocial().active)===ids,'NPC rerolled');});
 check('Friendly party can have several members',()=>{runRandom=()=>.8;enterEvent('npc_party');assert(ensureSocial().active.length===3,'no team');assert(document.querySelectorAll('#npc-scene-layer .npc-scene-actor').length===3,'team not displayed');});
 check('Bandit team starts real combat with summed HP',()=>{enterEvent('npc_bandits');const expected=ensureSocial().active.reduce((s,id)=>s+npcRecord(id).hp,0);chooseEvent(0);assert(gameState==='BATTLE'&&currentEnemy.npcIds.length===3,'no actual battle');assert(currentEnemy.originalHp===expected,'team HP inconsistent');saved();});
 check('NPC victory gives one reward and records wounds',()=>{enterEvent('npc_bandits');chooseEvent(0);currentEnemy.hp=0;endBattle('win');const gold=adventure.gold,loot=newLoot.uid;endBattle('win');assert(adventure.stats.wins===1&&adventure.gold===gold&&newLoot.uid===loot,'duplicate NPC award');assert(npcRecord('coin').hp<npcRecord('coin').maxHp,'NPC wounds missing');});
 check('Escape chance responds to stats and remains bounded',()=>{enterEvent('npc_bandits');hero.currentDodge=0;const a=npcCheckChance();hero.currentDodge=70;const b=npcCheckChance();assert(b>a&&a>=15&&b<=90,'wrong escape chance');});
 check('Successful event escape has no rewards',()=>{enterEvent('npc_bandits');const gold=adventure.gold;runRandom=()=>0;chooseEvent(2);assert(gameState==='RESULT'&&adventure.stats.wins===0&&adventure.gold===gold,'escape awarded loot');});
 check('Failed escape creates actual pursuit battle',()=>{enterEvent('npc_bandits');runRandom=()=>.99;chooseEvent(2);assert(gameState==='BATTLE'&&hero.hp<hero.maxHp,'no pursuit');});
 check('Battle escape completes once without victory rewards',()=>{startNpcBattle(['snip']);runRandom=()=>0;const gold=adventure.gold,xp=hero.exp;handleBattleAction('FLEE');handleBattleAction('FLEE');assert(gameState==='RESULT'&&adventure.stats.wins===0&&adventure.gold===gold&&hero.exp===xp&&ensureSocial().escapes===1,'bad escape settlement');saved();});
 check('Boss escape is rejected without consuming the turn',()=>{startBossBattle();const turn=totalTurnCount;handleBattleAction('FLEE');assert(gameState==='BATTLE'&&totalTurnCount===turn,'boss fled');});
 check('Temporary companion supports once per eligible round',()=>{recruitNpc('moss');enterMap();startSmallBattle(0);currentEnemy.hp=500;currentEnemy.originalHp=500;gameState='BATTLE_ACTION';adventure.battle.round=4;const n=npcSupport(),hp=currentEnemy.hp;assert(n>0&&npcSupport()===0&&hp===currentEnemy.hp,'support duplication');gameState='BATTLE';applySave(saved());assert(npcSupport()===0,'loaded support replay');});
 check('Companion ends after two settled battles',()=>{recruitNpc('iron');for(let i=0;i<2;i++){newLoot=null;startSmallBattle(0);currentEnemy.hp=0;endBattle('win');}assert(ensureSocial().helper===null&&ensureSocial().helperBattles===0,'helper never expires');});
 check('Thief cannot remove equipment or unlimited gold',()=>{adventure.gold=200;enterEvent('npc_pickpocket');const gear=JSON.stringify(hero.equipment);runRandom=()=>.99;chooseEvent(1);assert(adventure.gold===182&&JSON.stringify(hero.equipment)===gear,'unbounded theft');});
 check('Old save missing social ledger stays compatible',()=>{const d=captureSave();delete d.payload.adventure.expedition.social;const hp=hero.hp;applySave(d);assert(hero.hp===hp&&ensureSocial().version===1,'old save failed');});
 check('Malformed NPC or place is rejected before mutation',()=>{for(const kind of ['npc','place']){const before=JSON.stringify(captureSave().payload),d=captureSave();if(kind==='npc')d.payload.adventure.expedition.social.active=['not-a-person'];else d.payload.adventure.expedition.place='missing-place';let fail=false;try{applySave(d);}catch{fail=true;}assert(fail&&JSON.stringify(captureSave().payload)===before,'invalid data accepted');}});
 check('Twelve distinct named location variants',()=>assert(Object.keys(WORLD_PLACES).length===12,'places incomplete'));
 for(const id of Object.keys(NPC_ENCOUNTERS))for(let choice=0;choice<3;choice++)check(`${id} option ${choice+1}`,()=>{adventure.gold=100;if(id==='npc_camp')ensureSocial().active=['moss'];enterEvent(id);chooseEvent(choice);assert(STABLE_PHASES.includes(gameState),'nonplayable NPC outcome');saved();});
 Math.random=oldRandom;runRandom=oldRunRandom;return results;
});
await page.evaluate(()=>{confirmTitle();enterMap();});await page.screenshot({path:'v23-village.png',fullPage:false});
const views=[];for(const [width,height]of [[1280,900],[390,844],[320,568],[844,390]]){await page.setViewportSize({width,height});await page.evaluate(()=>{enterEvent('npc_bandits');});await page.waitForTimeout(80);const result=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,actors:document.querySelectorAll('#npc-scene-layer .npc-scene-actor').length,place:$('stage').dataset.place}));views.push(result);if(width===390)await page.screenshot({path:'v23-npc-mobile.png',fullPage:true});}
await page.setViewportSize({width:1280,height:900});for(const id of ['npc_tavern','npc_ambush','npc_wounded']){await page.evaluate(id=>enterEvent(id),id);await page.screenshot({path:`v23-place-${id}.png`,fullPage:false});}
fs.writeFileSync('npc-world-report.json',JSON.stringify({results,views,errors},null,2));console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,failures:results.filter(r=>!r.pass),views,errors},null,2));assert.ok(results.every(r=>r.pass)&&views.every(v=>v.width===v.scroll)&&errors.length===0);
}finally{await browser.close();}
