import { chromium } from 'playwright-core';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
await page.goto((process.env.GAME_URL||'http://127.0.0.1:8770/'),{waitUntil:'networkidle'});
const results=await page.evaluate(async()=>{
 const results=[],nativeRandom=Math.random,nativeNow=Date.now;
 const assert=(ok,why)=>{if(!ok)throw new Error(why);};
 const seeded=seed=>()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;};
 const reset=()=>{Math.random=seeded(271828);confirmTitle();actionDelay=0;};
 const checkSave=()=>parseSave(JSON.stringify(captureSave()));
 const ring=(id,tier=2)=>({name:RING_ABILITIES.find(a=>a.id===id).name,type:'RING',ability:RING_ABILITIES.find(a=>a.id===id),tier,rarity:'Rare'});
 const enemy=(values={})=>({...ENEMIES.SMALL[0],hp:50,def:0,mDef:0,dodge:0,exp:1,...values});
 const test=async(name,fn)=>{reset();try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}};
 await test('New run / initial save / title',(()=>{assert(gameState==='MAP','not map');assert(readSlot(SAVE_KEY).kind==='valid','initial save invalid');assert(hero.title.length>0,'missing title');}));
 await test('Dodge-counter kill grants XP and loot only once',()=>{
  Math.random=()=>0;hero.equipment.RING=ring('DODGE',4);createBattle(enemy({hp:1}));adventure.battle.nextMove='🌠';handleBattleAction('🛡️');
  assert(hero.exp===1,'XP duplicated');assert(adventure.stats.wins===1,'victory duplicated');assert(gameState==='LOOT_DECISION','reward not visible');const uid=newLoot.uid;
  endBattle('win');handleBattleAction('🛡️');assert(hero.exp===1&&newLoot.uid===uid,'late settlement duplicated reward');checkSave();
 });
 await test('Rapid battle input consumes a single round',async()=>{Math.random=()=>.5;createBattle(enemy({hp:9999}));adventure.battle.nextMove='🌠';for(let i=0;i<30;i++)handleBattleAction('⚔️');assert(totalTurnCount===1,'duplicate turn');await new Promise(r=>setTimeout(r,2));assert(gameState==='BATTLE','round lock stuck');checkSave();});
 await test('Burn death settles once and cannot reopen combat',async()=>{createBattle(enemy());hero.hp=1;hero.burnTurns=1;hero.burnDamage=3;for(let i=0;i<10;i++)handleBattleAction('⚔️');await new Promise(r=>setTimeout(r,2));assert(gameState==='DEFEAT','burn death not resolved');assert(adventure.stats.deaths===1,'duplicate death');assert(hero.hp===hero.maxHp,'no recovery');assert(totalTurnCount===1,'turn counted twice');checkSave();});
 await test('Fatal hit cannot be revived by block or reflection',()=>{Math.random=()=>0;hero.hp=1;hero.equipment.SHIELD.affixes=['S_BLOCK','S_REFLECT','S_BLOCK_CRIT'];hero.equipment.RING=ring('HEAL');createBattle(enemy({hp:1,atk:999}));hero.baseDodge=0;updateStatus();adventure.battle.nextMove='🌠';handleBattleAction('🛡️');assert(adventure.stats.deaths===1&&adventure.stats.wins===0,'fatal reflect counted as victory');});
 await test('Magic is never dodged / shield can be dodged',()=>{Math.random=()=>0;createBattle(enemy({dodge:100}));assert(!enemyDodged('🌠'),'magic was dodged');assert(enemyDodged('⚔️')&&enemyDodged('🛡️'),'physical evade ignored');});
 await test('Base dodge works without the dodge ring',()=>{Math.random=()=>0;hero.baseDodge=75;createBattle(enemy());const hp=hero.hp,ehp=currentEnemy.hp;monsterAttack('⚔️');assert(hero.hp===hp,'base dodge ignored');assert(currentEnemy.hp===ehp,'non-dodge ring countered');});
 await test('Overflow follow-up cannot recurse indefinitely',()=>{Math.random=()=>.2;hero.equipment.RING=ring('DODGE',4);hero.baseDodge=180;createBattle(enemy({hp:10000}));const hp=currentEnemy.hp;maybeExtraOverflowAttack();assert(currentEnemy.hp<hp,'overflow did not attack');assert(currentEnemy.hp>hp-200,'recursive overflow');assert(!overflowActive,'overflow guard stuck');});
 await test('Materials are retained while no equipment exists',()=>{addMaterials('WEAPON',9);addMaterials('SHIELD',8);assert(weaponMaterials===9&&shieldMaterials===8,'materials lost while empty');assert(hero.weaponRefineLevel===0,'unarmed refined');checkSave();});
 await test('Weapon replacement keeps the refine just earned',()=>{hero.equipment.WEAPON={type:'WEAPON',name:'Test old',power:15,rarity:'Magic',affixes:['W_CRIT_UP']};hero.weaponRefineLevel=2;weaponMaterials=4;offerLoot({type:'WEAPON',name:'Test new',power:45,rarity:'Rare',affixes:['W_ATK_UP'],refine:0,refineSlots:0});handleLootDecision('YES');assert(hero.weaponRefineLevel===3,'earned refine reset');assert(weaponMaterials===0,'wrong materials');assert(hero.equipment.WEAPON.affixes.includes('W_CRIT_UP'),'old affix lost');assert(hero.weaponRefineAffixes.length===1,'refine affix lost');checkSave();});
 await test('Low-value shield can be declined without losing refine',()=>{hero.equipment.SHIELD={type:'SHIELD',name:'Old shield',power:20,rarity:'Rare',refine:9,refineSlots:3,affixes:['S_BLOCK']};offerLoot({type:'SHIELD',name:'New shield',power:21,rarity:'Epic',refine:0,refineSlots:0,affixes:[]});handleLootDecision('NO');assert(hero.equipment.SHIELD.name==='Old shield'&&getShieldRefineLevel()===9,'shield silently replaced');assert(shieldMaterials===3,'bad shield salvage');checkSave();});
 await test('Double loot decision cannot consume twice',()=>{offerLoot(ring('MAGIC'));const uid=newLoot.uid;handleLootDecision('YES',uid);const stats=JSON.stringify(hero),gold=adventure.gold;handleLootDecision('NO',uid);assert(JSON.stringify(hero)===stats&&adventure.gold===gold,'double decision mutation');assert(adventure.stats.loot===1,'loot counted twice');});
 await test('Old item click token cannot affect the next item',()=>{offerLoot(ring('MAGIC'));const old=newLoot.uid;handleLootDecision('YES',old);enterMap();offerLoot(ring('DODGE'));const next=newLoot.uid;handleLootDecision('YES',old);assert(newLoot.uid===next&&gameState==='LOOT_DECISION','stale token consumed a different item');});
 await test('Same ring upgrades to the higher tier, never down',()=>{hero.equipment.RING=ring('MAGIC',1);offerLoot(ring('MAGIC',4));handleLootDecision('YES');assert(hero.equipment.RING.tier===4,'high tier discarded');enterMap();offerLoot(ring('MAGIC',1));handleLootDecision('YES');assert(hero.equipment.RING.tier===4,'max ring downgraded');});
 for(const ability of RING_ABILITIES){await test(`Round-trip ring ability ${ability.id}`,()=>{hero.equipment.RING=ring(ability.id,ability.id==='NONE'?0:4);updateStatus();const before=[hero.currentAttack,hero.currentDodge,hero.currentTieWinRate,getMagicAttackValue()];const saved=checkSave();applySave(saved);calculateHeroStats();assert(JSON.stringify(before)===JSON.stringify([hero.currentAttack,hero.currentDodge,hero.currentTieWinRate,getMagicAttackValue()]),'ring stats changed on load');if(ability.effect)assert(typeof hero.equipment.RING.ability.effect==='function','ability function not rehydrated');});}
 await test('All three bosses: one reward and a persistent ending',()=>{Math.random=()=>.5;for(let i=1;i<=3;i++){hero.level=20;hero.highestLevel=20;hero.maxHp=hero.hp=120;startBossBattle();currentEnemy.hp=0;endBattle('win');assert(bossLevel===i+1,'boss progress incorrect');assert(newLoot&&gameState==='LOOT_DECISION','boss reward skipped');endBattle('win');handleLootDecision('YES');if(i<3)enterMap();}assert(gameState==='CREDITS','missing ending');assert(adventure.stats.wins===3,'boss settlement duplicated');assert(readClearRecords().filter(r=>r.runId===adventure.runId).length===1,'clear not recorded once');showCredits();assert(readClearRecords().filter(r=>r.runId===adventure.runId).length===1,'replayed ending duplicated record');enterMap();assert(btn2.disabled,'completed boss button enabled');checkSave();});
 await test('Weapon rarity unlock gates are honored',()=>{hero.level=25;hero.highestLevel=25;for(const phase of [1,2,3]){bossLevel=phase;for(let i=0;i<1000;i++){const r=getRandomRarity('WEAPON');assert(phase>=2||!['Legendary','Mythic'].includes(r),'orange before boss one');assert(phase>=3||r!=='Mythic','mythic before boss two');}}});
 await test('Map event cannot overlap a new exploration',()=>{enterEvent('spring');const turns=totalTurnCount;for(let i=0;i<20;i++)handleMapAction('Small');assert(gameState==='EVENT'&&adventure.eventId==='spring','event overwritten');assert(totalTurnCount===turns,'locked action counted');});
 await test('Event choice applies once and survives a save',()=>{enterEvent('forge');adventure.gold=25;const saved=checkSave();applySave(saved);chooseEvent(0);chooseEvent(0);assert(adventure.gold===17,'event charged twice');assert(weaponMaterials===5,'event material duplicated');assert(adventure.stats.events===1,'event counted twice');checkSave();});
 await test('Courier and fox follow-ups occur after their flags',()=>{enterEvent('courier');chooseEvent(0);enterMap();adventure.steps=3;assert(pickEvent()==='delivery','courier follow-up missing');enterEvent('delivery');chooseEvent(1);assert(adventure.flags.delivered&&!adventure.flags.parcel,'parcel unresolved');enterMap();enterEvent('fox');chooseEvent(0);enterMap();adventure.steps=8;assert(pickEvent()==='foxGift','fox follow-up missing');checkSave();});

 for(const id of Object.keys(EVENTS))for(let pick=0;pick<3;pick++)await test(`Event ${id} / choice ${pick+1}`,()=>{adventure.gold=100;hero.level=5;hero.highestLevel=5;adventure.flags={fox:true,foxAt:0,parcel:true,parcelAt:0};enterEvent(id);chooseEvent(pick);assert(STABLE_PHASES.includes(gameState),'event left a transient state');checkSave();});
 for(const phase of ['MAP','BATTLE','EVENT','LOOT_DECISION','RESULT','DEFEAT','CREDITS'])await test(`Save/load stable phase ${phase}`,()=>{
  if(phase==='BATTLE')createBattle(enemy());if(phase==='EVENT')enterEvent('bridge');if(phase==='LOOT_DECISION')offerLoot(ring('DODGE'));if(phase==='RESULT')resultEvent('Test','Result text');if(phase==='DEFEAT'){createBattle(enemy());hero.hp=0;endBattle('lose');}if(phase==='CREDITS'){bossLevel=4;showCredits();}
  const doc=checkSave();applySave(doc);assert(gameState===phase,'phase changed on load');assert(!document.querySelector('#command-menu').hidden||!document.querySelector('#decision-menu').hidden,'no controls after load');checkSave();
 });
 await test('Save mid-animation resumes the already resolved next round',async()=>{createBattle(enemy({hp:9999}));adventure.battle.nextMove='🌠';handleBattleAction('⚔️');assert(gameState==='BATTLE_ACTION','no action lock');const round=adventure.battle.round,enemyHP=currentEnemy.hp,doc=checkSave();applySave(doc);await new Promise(r=>setTimeout(r,3));assert(gameState==='BATTLE'&&adventure.battle.round===round&&currentEnemy.hp===enemyHP,'action replayed after load');});
 await test('Stale callback cannot interrupt a loaded map',async()=>{const map=checkSave();createBattle(enemy({hp:9999}));adventure.battle.nextMove='🌠';handleBattleAction('⚔️');applySave(map);await new Promise(r=>setTimeout(r,3));assert(gameState==='MAP'&&currentEnemy===null,'old action overwrote loaded state');});
 await test('Pending loot reload does not roll or grant again',()=>{offerLoot(ring('HEAL',3));const uid=newLoot.uid,doc=checkSave();applySave(doc);assert(newLoot.uid===uid&&newLoot.tier===3,'loot rerolled');handleLootDecision('YES');assert(adventure.stats.loot===1,'loot not consumed once');});
 await test('Manual slot is not overwritten by autosave',()=>{writeSave(SAVE_KEY+'.1',captureSave());const manual=localStorage.getItem(SAVE_KEY+'.1');adventure.gold+=10;saveAuto();assert(localStorage.getItem(SAVE_KEY+'.1')===manual,'manual overwritten');assert(readSlot(SAVE_KEY).doc.payload.adventure.gold===35,'auto missing change');});
 await test('Corrupt automatic save falls back to valid backup',()=>{saveAuto();localStorage.setItem(SAVE_KEY,'{broken');const best=getBestSave();assert(best?.recovered,'no backup recovery');applySave(best.doc);assert(readSlot(SAVE_KEY).kind==='valid','recovery failed');});
 await test('Unavailable storage does not crash the game',()=>{const original=Storage.prototype.setItem;try{Storage.prototype.setItem=function(){throw new DOMException('test quota','QuotaExceededError');};assert(saveAuto()===false,'reported false success');enterEvent('spring');chooseEvent(0);assert(gameState==='RESULT','game crashed on storage error');}finally{Storage.prototype.setItem=original;saveAuto();}});
 for(const [name,mutate]of [
  ['zero XP threshold',d=>d.payload.hero.expToNextLevel=0],['negative HP',d=>d.payload.hero.hp=-1],['unknown ability',d=>d.payload.hero.equipment.RING.ability={id:'UNKNOWN'}],['ring tier overflow',d=>d.payload.hero.equipment.RING.tier=999],['bad phase',d=>d.payload.gameState='SETTLING'],['missing loot',d=>d.payload.gameState='LOOT_DECISION'],['NaN stats',d=>d.payload.hero.baseAttack=NaN],['oversized story',d=>d.payload.hero.name='x'.repeat(20000)],['invalid event',d=>{d.payload.gameState='EVENT';d.payload.adventure.eventId='unseen';}]
 ])await test(`Reject corrupt save: ${name}`,()=>{const doc=captureSave(),before=JSON.stringify(captureSave().payload);mutate(doc);let failed=false;try{applySave(doc);}catch{failed=true;}assert(failed,'corrupt save accepted');assert(JSON.stringify(captureSave().payload)===before,'state mutated before validation');});
 await test('Import parser rejects prototype keys',()=>{let failed=false;try{parseSave('{"__proto__":{"polluted":true}}');}catch{failed=true;}assert(failed&&!({}).polluted,'unsafe object accepted');});
 await test('Imported display text cannot become HTML',()=>{const doc=captureSave();doc.payload.hero.name=doc.payload.hero.title='<img src=x onerror=alert(1)>';applySave(doc);assert($('hero-title').querySelector('img')===null,'markup interpreted');assert($('hero-title').textContent.startsWith('<img'),'text not preserved safely');});
 await test('Rest is single-use during its cooldown',()=>{for(let i=0;i<30;i++)handleMapAction('Heal');assert(adventure.stats.rests===1&&totalTurnCount===1,'rest double counted');checkSave();});
 Math.random=nativeRandom;Date.now=nativeNow;
 return results;
});
fs.writeFileSync('regression-report.json',JSON.stringify({timestamp:new Date().toISOString(),results,errors},null,2));
console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass),errors},null,2));
await browser.close();
if(results.some(r=>!r.pass)||errors.length)process.exitCode=1;
